### ISSUE TITLE
Cannot find module './parser/satisfactory/types/property/special/SpecialAnyProperties'

### ISSUE THREAD

**Issue by Sleavely** [etothepii4/satisfactory-file-parser#1]
I was just about to fork and submit a PR for the "totalLength" property on ConveyorChainActor when I noticed you updated it in 2f238b3fdeb61c596e59cb5712719e0b7e1aaa46 :D

However, it looks like the exports in `./src/index.ts` need some refreshing now. This file doesn't exist anymore:

https://github.com/etothepii4/satisfactory-file-parser/blob/2f238b3fdeb61c596e59cb5712719e0b7e1aaa46/src/index.ts#L28

**Comment by etothepii4** [comment]
Thank you for your thoughts on this!
You are right, the last commit was not tested and had residual errors. That is on me.

**Comment by etothepii4** [comment]
I fixed the residual errors in b9b4952 now. So the issue should be fixed.
The errors included a part of your other PR regarding using the BinaryReadable argument. So i figure it made sense to have that implemented already with the issue fix.

**Comment by Sleavely** [comment]
Awesome, thanks! I'll rename the PR since it now only adds `tsc --noEmit`  to `npm test`
